name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.7.3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: terraform_plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: success()
        run: terraform apply tfplan

      - name: Create Issue on Failure
        if: failure()
        uses: actions/create-issue@v1
        with:
          title: Deployment Failure
          body: |
            An error occurred during the deployment process. Please investigate and resolve the issue.
            Error details:
            ```
            ${{ steps.terraform_plan.outputs.stdout }}
            ```
